/**
 * Your application code goes here<br>
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */


package userclasses;

import com.codename1.io.Storage;
import generated.StateMachineBase;
import com.codename1.ui.*; 
import com.codename1.ui.events.*;
import com.codename1.ui.util.Resources;
import java.util.Vector;

/**
 *
 * @author Your name here
 */

public class StateMachine extends StateMachineBase {
    public StateMachine(String resFile) {
        super(resFile);
        // do not modify, write code in initVars and initialize class members there,
        // the constructor might be invoked too late due to race conditions that might occur
    }
    
    /**
     * this method should be used to initialize variables instead of
     * the constructor/class scope to avoid race conditions
     */
    protected void initVars(Resources res) {
    }

    public int i = -1;
    @Override
    protected void onMain_SaveAction(Component c, ActionEvent event) {
        
        ++i;
        //creating a label for memos
        Label top = new Label();
        top.setTextPosition(Component.TOP);
        c.getComponentForm().add(top);
        top.setName("Data" + top.getComponentForm().getComponentCount());
        
        //saving text
        String text = findTxt(c).getText();
        Vector<String> vec = new Vector<String>();
        vec.addElement(text);
        Storage.getInstance().writeObject("SavedData", vec);
        
        //loading text
        vec = (Vector<String>)Storage.getInstance().readObject("SavedData");
        findData(c).setText(vec.elementAt(0));
        c.getComponentForm().revalidate();
    }
}

  
